# Conda environment configuration for Gel Blot Analyzer
#
# To create this environment, run:
# > conda env create -f environment.yml
#
# To activate this environment, run:
# > conda activate gel_analyzer_env
#
name: gel_analyzer_env  # Updated environment name

channels:
  - defaults
  - conda-forge

dependencies:
  # --- Core ---
  - python=3.9         # Specify a stable Python version

  # --- GUI Framework ---
  - pyside6            # The core library for the application's user interface

  # --- Scientific & Data Handling (from Conda) ---
  - numpy              # Fundamental package for numerical operations
  - scipy              # For scientific algorithms (signal processing, interpolation)
  - scikit-image       # For advanced image processing algorithms (e.g., rolling ball)
  - pillow             # For core image file I/O and manipulation
  - openpyxl           # For reading and writing Excel (.xlsx) files

  # --- Plotting ---
  - matplotlib         # For generating all scientific plots and graphs

  # --- Application Bundling (Optional) ---
  - pyinstaller        # For compiling the script into a standalone application

  # --- Additional packages installed via pip ---
  # to ensure maximum compatibility and prevent unexpected breakages.
  - pip
  - pip:
    - svgwrite       # For exporting images to the scalable SVG format
    - opencv-python  # For core computer vision functionality (used for transforms)
    - opencv-contrib-python # For core computer vision functionality (used for transforms)
