{\rtf1\ansi\ansicpg1252\cocoartf2820
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\froman\fcharset0 Times-Roman;}
{\colortbl;\red255\green255\blue255;\red80\green91\blue117;}
{\*\expandedcolortbl;;\cssrgb\c38824\c43529\c53333;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs25\fsmilli12573 \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 name: imaging_assistant_env  # Name of the Conda environment\
channels:\
  - defaults\
  - conda-forge\
dependencies:\
  - python=3.9  # Specify the Python version\
  - pyqt=5.15  # PyQt5 for the GUI\
  - numpy  # For numerical operations\
  - scipy  # For scientific computing\
  - matplotlib  # For plotting\
  - scikit-image  # For image processing\
  - openpyxl  # For Excel file handling\
  - pillow  # For image manipulation\
  - pip  # For installing additional Python packages\
  - pip:\
    - svgwrite  # For SVG file handling (if not available via Conda)}